name: tfc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.1.19=h06a4308_1
  - certifi=2020.12.5=py39h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1j=h27cfd23_0
  - pip=21.0.1=py39h06a4308_0
  - python=3.9.2=hdb3f193_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py39h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - tzdata=2020f=h52ac0ba_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - joblib==1.0.1
    - numpy==1.20.1
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - threadpoolctl==2.1.0
    - torch==1.8.0
    - typing-extensions==3.7.4.3
    - sentence-transformers==2.1.0
    - pandas==1.4.0
    - pytorch_lightning==1.5.9
    - matplotlib==3.5.0
    - SPARQLWrapper==1.8.5
    - networkx==2.6.3
    - torchmetrics
    - huggingface_hub
    - chardet
#if cuda issue with pytorch following command is needed in extra to execute seperately
#pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
prefix: /home/envs/tfc
